spring.application.name=portfolio-site
spring.datasource.url=jdbc:postgresql://localhost:5432/db_portfolio
spring.datasource.username=postgres
spring.datasource.password=aeAJXsNc8KCojtDFhxJU7YnWJiY2WcQP0nc5aTwMuno7

# Path of the OpenAPI documentation
springdoc.api-docs.path=/api-docs
# Path of the Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html